import { Inter } from "next/font/google";
import "./globals.css";
import AnimatedDots from "./components/AnimatedDots";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "MFV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <AnimatedDots />
        {children}
      </body>
    </html>
  );
}
