import { Audiowide } from "next/font/google";
import "./globals.css";
import AnimatedDots from "./components/AnimatedDots";

const audiowide = Audiowide({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-audiowide",
});

export const metadata = {
  title: "MFV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        {/* You can add other meta tags here as needed */}
      </head>
      <body className={`${audiowide.variable} antialiased`}>
        <AnimatedDots />
        {children}
      </body>
    </html>
  );
}
